package br.com.java.triadic.contextgenerator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Josué
 */
public class MainGUI extends javax.swing.JFrame {

    private File file;
    private ContextFormatter triadicContext;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        saveJsonButton.setEnabled(false);
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        selectFileButton = new javax.swing.JButton();
        saveJsonButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        condsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        attrsList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        objectsSize = new javax.swing.JLabel();
        attrsSize = new javax.swing.JLabel();
        condsSize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputObjects = new javax.swing.JTextField();
        inputAttributes = new javax.swing.JTextField();
        inputConditions = new javax.swing.JTextField();
        saveContextButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de Contexto Triádico");
        setMaximumSize(new java.awt.Dimension(470, 280));
        setMinimumSize(new java.awt.Dimension(470, 280));
        setResizable(false);

        jTextField1.setEditable(false);

        selectFileButton.setText("Selecionar Arquivo...");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        saveJsonButton.setText("Salvar JSON");
        saveJsonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJsonButtonActionPerformed(evt);
            }
        });

        condsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                condsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(condsList);

        objectsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                objectsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(objectsList);

        attrsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                attrsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(attrsList);

        jLabel6.setText("Objetos:");

        jLabel7.setText("Atributos:");

        jLabel8.setText("Condições:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(objectsSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attrsSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(condsSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveJsonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(objectsSize)
                    .addComponent(attrsSize)
                    .addComponent(condsSize))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveJsonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Gerar JSON", jPanel1);

        jLabel1.setText("Nome:");

        inputName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Quantidade de objetos:");

        jLabel4.setText("Quantidade de atributos:");

        jLabel5.setText("Quantidade de condições:");

        saveContextButton.setText("Salvar JSON");
        saveContextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveContextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(saveContextButton))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputObjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputConditions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveContextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Gerar Contexto Triádico", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            jTextField1.setText(file.getAbsolutePath());
            saveJsonButton.setEnabled(true);

            jProgressBar1.setVisible(true);
            jProgressBar1.setIndeterminate(true);
            saveJsonButton.setEnabled(false);

            new Thread(() -> {
                triadicContext = new ContextFormatter(file);
                if (triadicContext.readFile() && triadicContext.buildRelations()) {
                    
                    objectsList.setListData(triadicContext.getObjects().toArray(new String[0]));
                    attrsList.setListData(triadicContext.getAttributes().toArray(new String[0]));
                    condsList.setListData(triadicContext.getConditions().toArray(new String[0]));
                    
                    objectsSize.setText(String.valueOf(triadicContext.getObjects().size()));
                    attrsSize.setText(String.valueOf(triadicContext.getAttributes().size()));
                    condsSize.setText(String.valueOf(triadicContext.getConditions().size()));
                    
                } else {
                    JOptionPane.showMessageDialog(MainGUI.this, "Ocorreu um erro ao carregar arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                jProgressBar1.setIndeterminate(false);
                jProgressBar1.setVisible(false);
                saveJsonButton.setEnabled(true);
            }).start();
        }

    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void saveJsonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJsonButtonActionPerformed
        jProgressBar1.setVisible(true);
        jProgressBar1.setIndeterminate(true);
        saveJsonButton.setEnabled(false);

        new Thread(() -> {
            if (triadicContext != null) {
                JFileChooser fc = new JFileChooser();
                int returnVal = fc.showSaveDialog(MainGUI.this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {

                    try (Writer writer = new FileWriter(fc.getSelectedFile() + ".json")) {
                        
                        List<String> objts = 
                                objectsList.getSelectedValuesList().size() > 0 ?
                                objectsList.getSelectedValuesList() :
                                triadicContext.getObjects();
                        
                        List<String> attrs = 
                                attrsList.getSelectedValuesList().size() > 0 ?
                                attrsList.getSelectedValuesList() :
                                triadicContext.getAttributes();
                        
                        List<String> conds = 
                                condsList.getSelectedValuesList().size() > 0 ?
                                condsList.getSelectedValuesList() :
                                triadicContext.getConditions();
                        
                        triadicContext.filter(objts, attrs, conds).generateJSON(writer);
                        
                        JOptionPane.showMessageDialog(MainGUI.this, String.format(
                                "%d objetos, %d atributos e %d condições",
                                objts.size(),
                                attrs.size(),
                                conds.size()), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(MainGUI.this, "Ocorreu um erro ao gerar arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(MainGUI.this, "Ocorreu um erro ao gerar arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            jProgressBar1.setIndeterminate(false);
            jProgressBar1.setVisible(false);
            saveJsonButton.setEnabled(true);
        }).start();
    }//GEN-LAST:event_saveJsonButtonActionPerformed

    private void saveContextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveContextButtonActionPerformed
        String name = null;
        int objs = 0, attrs = 0, conds = 0;
        try {
            name = inputName.getText();
            objs = Integer.parseInt(inputObjects.getText());
            attrs = Integer.parseInt(inputAttributes.getText());
            conds = Integer.parseInt(inputConditions.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(MainGUI.this, "Verifique os valores dos campos..", "Valor inserido inválido!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        final ContextGenerator cg = new ContextGenerator(name, objs, attrs, conds);

        jProgressBar1.setVisible(true);
        jProgressBar1.setIndeterminate(true);
        saveJsonButton.setEnabled(false);

        new Thread(() -> {
            JFileChooser fc = new JFileChooser();
            int returnVal = fc.showSaveDialog(MainGUI.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {

                try (Writer writer = new FileWriter(fc.getSelectedFile() + ".json")) {
                    cg.generateJSON(writer);
                    JOptionPane.showMessageDialog(MainGUI.this, String.format(
                            "%d objetos, %d atributos e %d condições",
                            cg.getObjects().size(),
                            cg.getAttributes().size(),
                            cg.getConditions().size()), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(MainGUI.this, "Ocorreu um erro ao gerar arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            jProgressBar1.setIndeterminate(false);
            jProgressBar1.setVisible(false);
            saveJsonButton.setEnabled(true);
        }).start();
    }//GEN-LAST:event_saveContextButtonActionPerformed

    private void objectsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_objectsListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            int objts = objectsList.getSelectedValuesList().size();
            objectsSize.setText(String.valueOf(objts));
        }
    }//GEN-LAST:event_objectsListValueChanged

    private void attrsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_attrsListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            int attrs = attrsList.getSelectedValuesList().size();
            attrsSize.setText(String.valueOf(attrs));
        }
    }//GEN-LAST:event_attrsListValueChanged

    private void condsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_condsListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            int conds = condsList.getSelectedValuesList().size();
            condsSize.setText(String.valueOf(conds));
        }
    }//GEN-LAST:event_condsListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> attrsList;
    private javax.swing.JLabel attrsSize;
    private javax.swing.JList<String> condsList;
    private javax.swing.JLabel condsSize;
    private javax.swing.JTextField inputAttributes;
    private javax.swing.JTextField inputConditions;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputObjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> objectsList;
    private javax.swing.JLabel objectsSize;
    private javax.swing.JButton saveContextButton;
    private javax.swing.JButton saveJsonButton;
    private javax.swing.JButton selectFileButton;
    // End of variables declaration//GEN-END:variables
}
